# Generated by Django 5.1.3 on 2025-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumShotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits', models.CharField(max_length=64)),
                ('number', models.BigIntegerField()),
                ('batch_id', models.CharField(max_length=200)),
                ('shot_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
