# Generated by Django 5.1.3 on 2025-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantumshotresult',
            name='used_bits',
            field=models.IntegerField(default=0, max_length=26),
        ),
    ]
